### ISSUE TITLE
Update assets

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/digest#15]
As @ocean90 noted, this should use more like a mail/envelope icon than a megaphone.

@velthy Any ideas? :)

**Comment by velthy** [comment]
Here are some ideas for the icon and cover image.
The version with the star has a heavy sowjet-feeling to it. Especially the icon on the red background.
I'd prefer the heart version.

![digest-banner-heart](https://user-images.githubusercontent.com/3276054/28155316-76f3abae-67ae-11e7-8fe6-59417839bc16.png)
![digest-banner-star](https://user-images.githubusercontent.com/3276054/28155318-77098708-67ae-11e7-816e-8304c94d3a71.png)
![digest-icon-heart](https://user-images.githubusercontent.com/3276054/28155319-770d49ce-67ae-11e7-9e6e-78499d59d978.png)
![digest-icon-star](https://user-images.githubusercontent.com/3276054/28155320-77100d08-67ae-11e7-85f3-fbd856f8c4bd.png)

**Comment by grappler** [comment]
I can see the thing with the star. I am not sure if the heart represents the contents on the email.

As some of the notifications will be about comments I thought of using the discussion icons
https://developer.wordpress.org/resource/dashicons/#admin-comments
https://developer.wordpress.org/resource/dashicons/#format-chat

OR if thinking generally of notifications a flag or lightbulb.
https://developer.wordpress.org/resource/dashicons/#flag
https://developer.wordpress.org/resource/dashicons/#lightbulb

**Comment by ocean90** [comment]
Or a bell; notifications (🔔) wrapped in a mail( ✉️).

**Comment by grappler** [comment]
Does @velthy approve of my design? 😛 

![image](https://user-images.githubusercontent.com/1785641/47337217-533f6400-d693-11e8-9ff4-0adca64a64af.png)

![image](https://user-images.githubusercontent.com/1785641/47337199-3efb6700-d693-11e8-8cf2-08ad2092ce06.png)

**Comment by velthy** [comment]
It seems a bit too complex. Not because of the bell, but the triangle on top. Can you try it without?

**Comment by grappler** [comment]
@velthy Here without the triangle
![image](https://user-images.githubusercontent.com/1785641/47339585-f5634a00-d69b-11e8-90ce-1ad8515b5531.png)

![image](https://user-images.githubusercontent.com/1785641/47339596-fd22ee80-d69b-11e8-8b72-7127884db679.png)

**Comment by ocean90** [comment]
How about using a more "flat" version of the icon? Something like https://thenounproject.com/term/bell/307/.

Also wondering if we should add a small number into the bell since that’s the feature of the plugin. Many notifications in one mail.

**Comment by grappler** [comment]
> How about using a more "flat" version of the icon?

I don't see the big difference. A flat version for me would be: https://thenounproject.com/term/bell/28635/

> add a small number into the bell

Normally the notification number is on the side instead of the middle of the icon/bell

**Comment by ocean90** [comment]
Not that flat...

Another example:
![20579436](https://user-images.githubusercontent.com/617637/47341574-a7e9db80-d6a1-11e8-90fb-39633dfa0a1d.jpg)

**Comment by grappler** [comment]
Next attempt with different icon. The notification number is not there yet.

![image](https://user-images.githubusercontent.com/1785641/47380081-e660b400-d6fc-11e8-8a8e-fbfda72c2752.png)
![image](https://user-images.githubusercontent.com/1785641/47380092-ed87c200-d6fc-11e8-8478-470302027f76.png)

**Comment by velthy** [comment]
Here is one version with a simplified bell and notification bubble. I don't think it's necessary to include a number.

![digest-banner-772x250](https://user-images.githubusercontent.com/3276054/47548898-aa933d80-d8fa-11e8-820a-d31d739b1562.png)
![digest-icon-256x256](https://user-images.githubusercontent.com/3276054/47548899-aa933d80-d8fa-11e8-8628-755dd7cebae9.png)
