### ISSUE TITLE
Spam comments notifications 

### ISSUE THREAD

**Issue by grappler** [wearerequired/digest#8]
I have installed the plugin but I am still getting single spam comments notifications. I am using the latest version of the plugin, WordPress and Anti spam bee.

**Comment by swissspidy** [comment]
Do you mean the single spam comment notification mails sent by Antispam Bee? Because ASB isn't supported yet. See #1.

**Comment by grappler** [comment]
I think so. I was getting an email every time there was a spam comment. It would be great if it could be supported.

**Comment by swissspidy** [comment]
Closing in favour of #1.
